<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  
      <AspireVersion>9.2.0</AspireVersion>
      <CommunityToolkitAspireVersion>9.3.0</CommunityToolkitAspireVersion>
      <CommunityToolkitAspireVersionBeta>9.4.1-beta.291</CommunityToolkitAspireVersionBeta>
    <AspNetCoreVersion>10.0.0</AspNetCoreVersion>
    <OpenTelemetryVersion>1.9.0</OpenTelemetryVersion>
  
    <IsPackable>false</IsPackable>
</PropertyGroup>
</Project>
  